pipeline {
    agent any

    environment {
        // Using a virtual environment is a best practice for Python projects
        // to isolate dependencies.
        VENV = "venv"
    }

    stages {
        stage('Build and Test') {
            // Change directory to where the Jenkinsfile and source code are located
            dir('pipeline-python-yml') {
                stage('Setup Virtual Environment') {
                    steps {
                        script {
                            // Ensure we have a clean environment
                            sh "python3 -m venv ${VENV}"
                        }
                    }
                }

                stage('Install Dependencies') {
                    steps {
                        // Activate virtualenv and install dependencies.
                        // pytest is a popular testing framework.
                        // flake8 is a linter to check for code style.
                        sh ". ${VENV}/bin/activate && pip install pytest flake8"
                    }
                }

                stage('Linting') {
                    steps {
                        // Run flake8 to check for code quality and style.
                        sh ". ${VENV}/bin/activate && flake8 src/ test/"
                    }
                }

                stage('Test') {
                    steps {
                        // Run tests with pytest. It will automatically discover tests.
                        sh ". ${VENV}/bin/activate && pytest"
                    }
                }
            }
        }
    }
}